// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::chassisLeftFrontMotor;
std::shared_ptr<SpeedController> RobotMap::chassisrightFrontMotor;
std::shared_ptr<SpeedController> RobotMap::chassisleftRearMotor;
std::shared_ptr<SpeedController> RobotMap::chassisrightRearMotor;
std::shared_ptr<RobotDrive> RobotMap::chassisRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    chassisLeftFrontMotor.reset(new Talon(0));
    lw->AddActuator("Chassis", "LeftFrontMotor", (Talon&) chassisLeftFrontMotor);
    
    chassisrightFrontMotor.reset(new Talon(1));
    lw->AddActuator("Chassis", "rightFrontMotor", (Talon&) chassisrightFrontMotor);
    
    chassisleftRearMotor.reset(new Talon(2));
    lw->AddActuator("Chassis", "leftRearMotor", (Talon&) chassisleftRearMotor);
    
    chassisrightRearMotor.reset(new Talon(3));
    lw->AddActuator("Chassis", "rightRearMotor", (Talon&) chassisrightRearMotor);
    
    chassisRobotDrive41.reset(new RobotDrive(chassisLeftFrontMotor, chassisleftRearMotor,
              chassisrightFrontMotor, chassisrightRearMotor));
    
    chassisRobotDrive41->SetSafetyEnabled(true);
        chassisRobotDrive41->SetExpiration(0.1);
        chassisRobotDrive41->SetSensitivity(0.5);
        chassisRobotDrive41->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
